Backup scripts.

diff --git a/01-core/pi-server-backup b/01-core/pi-server-backup
--- a/01-core/pi-server-backup
+++ b/01-core/pi-server-backup
@@ -10,6 +10,7 @@ SERVICES_DIR='@@@@@6@@@@@'
 LOG='@@@@@7@@@@@'
 GIT_BACKUP_CONFIG='@@@@@8@@@@@'
 GIT_DIR='@@@@@9@@@@@'
+GIT_SSH_SCRIPT='@@@@@10@@@@@'
 HAS_LOCK=''
 
 function lock() {
@@ -127,12 +128,12 @@ if [ -f "${GIT_BACKUP_CONFIG}" ]; then
         if [ ! -e "${REPO_PATH}" ]; then
             echo "Cloning to ${REPO_PATH}..." >> "${LOG}"
             cd /
-            su -s /bin/bash -c "git clone --mirror '${line}' '${REPO_PATH}'" www-data &>> "${LOG}" || fail 'Cloning a repository failed.'
+            su -s /bin/bash -c "export GIT_SSH='${GIT_SSH_SCRIPT}' && git clone --mirror '${line}' '${REPO_PATH}'" www-data &>> "${LOG}" || fail 'Cloning a repository failed.'
             echo "Cloned to ${REPO_PATH}." >> "${LOG}"
         else
             echo "Updating ${REPO_PATH}..." >> "${LOG}"
             cd /
-            su -s /bin/bash -c "cd '${REPO_PATH}' && git fetch --all && git fetch --all --tags" www-data &>> "${LOG}" || fail 'Fetching a repository failed.'
+            su -s /bin/bash -c "export GIT_SSH='${GIT_SSH_SCRIPT}' && cd '${REPO_PATH}' && git fetch --all && git fetch --all --tags" www-data &>> "${LOG}" || fail 'Fetching a repository failed.'
             echo "Updated ${REPO_PATH}." >> "${LOG}"
         fi
     done < "${GIT_BACKUP_CONFIG}"
