Certificate scripts.

diff --git a/00-ca/00-make-ca b/00-ca/00-make-ca
--- a/00-ca/00-make-ca
+++ b/00-ca/00-make-ca
@@ -14,18 +14,44 @@ test -e "${1}" && usage
 
 CA_DIR="${1}"
 
+
+printf "Enter the new password for the root CA key: " &&
+read -s PASSWD &&
+echo &&
+
+printf "Enter the password again to confirm: " &&
+read -s PASSWD2 &&
+echo &&
+
+if [ "${PASSWD}" != "${PASSWD2}" ]; then
+    echo "Error: the passwords do not match"
+    exit 1
+fi
+
+
 mkdir -p "${CA_DIR}" &&
 mkdir -p "${CA_DIR}/ca" &&
 mkdir -p "${CA_DIR}/data" &&
 cp -a "${DIR}/scripts" "${CA_DIR}/scripts" &&
 cp "${DIR}/openssl.conf" "${CA_DIR}/openssl.conf" &&
 touch "${CA_DIR}/data/index.txt" &&
-echo 0 > "${CA_DIR}/data/serial.txt" &&
+echo 00 > "${CA_DIR}/data/serial.txt" &&
+chmod -R go-rwx "${CA_DIR}" &&
 
 export CA_DIR &&
-openssl req -config "${CA_DIR}/openssl.conf" -x509 -newkey rsa -keyout "${CA_DIR}/ca/ca.key" -out "${CA_DIR}/ca/ca.crt" -outform PEM &&
+
+exec 3<<EOF
+${PASSWD}
+EOF
+
+openssl req -config "${CA_DIR}/openssl.conf" -x509 -newkey rsa -keyout "${CA_DIR}/ca/ca.key" -out "${CA_DIR}/ca/ca.crt" -outform PEM -passout fd:3 &&
+
 chmod u=r "${CA_DIR}/ca/ca.crt" "${CA_DIR}/ca/ca.key" &&
 chmod go-rwx "${CA_DIR}/ca/ca.key" &&
-chmod go=r "${CA_DIR}/ca/ca.crt"
+chmod go=r "${CA_DIR}/ca/ca.crt" &&
 
-# openssl ca -config "${CA_DIR}/openssl.conf" -gencrl
+exec 3<<EOF
+${PASSWD}
+EOF
+
+openssl ca -config "${CA_DIR}/openssl.conf" -gencrl -out "${CA_DIR}/ca/crl" -passin fd:3
diff --git a/00-ca/scripts/make-client-cert b/00-ca/scripts/make-client-cert
--- a/00-ca/scripts/make-client-cert
+++ b/00-ca/scripts/make-client-cert
@@ -1,4 +1,60 @@
 #!/bin/bash
 
 export CA_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.." &&
-openssl ca 
+
+printf "Enter the certificate's name: " &&
+read CERT_NAME &&
+
+if [ -z "${CERT_NAME}" ]; then
+    echo "Certificate name must not be empty"
+    exit 1
+fi
+
+printf "Enter the password for the root CA key: " &&
+read -s PASSWD &&
+echo &&
+
+
+printf "Enter the password for the new PKCS#12 file: " &&
+read -s PKCS_PASSWD &&
+echo &&
+
+printf "Enter the new PKCS#12 password again: " &&
+read -s PKCS_PASSWD2 &&
+echo &&
+
+if [ "${PKCS_PASSWD}" != "${PKCS_PASSWD2}" ]; then
+    echo "The passwords do not match"
+    exit 1
+fi
+
+
+CERT_DIR="${CA_DIR}/certs/client/${CERT_NAME}__$(date '+%Y_%m_%d_%H_%M_%S')" &&
+mkdir -p "${CERT_DIR}" &&
+
+# Certificate request
+openssl req -config "${CA_DIR}/openssl.conf" -new -subj "/C=GB/O=Callum J. Cameron/CN=${CERT_NAME}" -newkey rsa -keyout "${CERT_DIR}/${CERT_NAME}.key" -out "${CERT_DIR}/${CERT_NAME}.csr" -outform PEM -nodes &&
+
+
+# Sign
+exec 3<<EOF
+${PASSWD}
+EOF
+
+openssl ca -config "${CA_DIR}/openssl.conf" -in "${CERT_DIR}/${CERT_NAME}.csr" -out "${CERT_DIR}/${CERT_NAME}.crt" -outdir "${CA_DIR}/data" -batch -passin fd:3 &&
+
+
+# Make PKCS#12 file
+exec 3<<EOF
+${PKCS_PASSWD}
+EOF
+
+openssl pkcs12 -export -out "${CERT_DIR}/${CERT_NAME}.p12" -in "${CERT_DIR}/${CERT_NAME}.crt" -inkey "${CERT_DIR}/${CERT_NAME}.key" -name "${CERT_NAME}" -passin pass: -passout fd:3 &&
+
+
+# Cleanup
+rm "${CERT_DIR}/${CERT_NAME}.csr" &&
+chmod u=r "${CERT_DIR}/${CERT_NAME}.key" "${CERT_DIR}/${CERT_NAME}.crt" "${CERT_DIR}/${CERT_NAME}.p12" &&
+chmod go=r "${CERT_DIR}/${CERT_NAME}.crt" &&
+chmod go-rwx "${CERT_DIR}/${CERT_NAME}.key" "${CERT_DIR}/${CERT_NAME}.p12" &&
+cp "${CA_DIR}/ca/ca.crt" "${CERT_DIR}"
diff --git a/00-ca/scripts/make-pi-server-certs b/00-ca/scripts/make-pi-server-certs
--- a/00-ca/scripts/make-pi-server-certs
+++ b/00-ca/scripts/make-pi-server-certs
@@ -1,1 +1,46 @@
 #!/bin/bash
+
+export CA_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.." &&
+
+printf "Enter the domain name or IP address on which the server's owncloud instance will be accessed: " &&
+read SERVER_ADDR &&
+
+if [ -z "${SERVER_ADDR}" ]; then
+    echo "Server address must not be empty"
+    exit 1
+fi
+
+printf "Enter the password for the root CA key: " &&
+read -s PASSWD &&
+echo &&
+
+CERT_DIR="${CA_DIR}/certs/server/${SERVER_ADDR}__$(date '+%Y_%m_%d_%H_%M_%S')" &&
+mkdir -p "${CERT_DIR}" &&
+
+function do-cert()
+{
+    # Certificate request
+    openssl req -config "${CA_DIR}/openssl.conf" -new -subj "/C=GB/O=Callum J. Cameron/CN=${1}" -newkey rsa -keyout "${CERT_DIR}/${2}.key" -out "${CERT_DIR}/${2}.csr" -outform PEM -nodes &&
+
+    # Sign
+    exec 3<<EOF
+${PASSWD}
+EOF
+    openssl ca -config "${CA_DIR}/openssl.conf" -in "${CERT_DIR}/${2}.csr" -out "${CERT_DIR}/${2}.crt" -outdir "${CA_DIR}/data" -extensions server -batch -passin fd:3 &&
+
+    # Cleanup
+    rm "${CERT_DIR}/${2}.csr" &&
+    chmod u=r "${CERT_DIR}/${2}.key" "${CERT_DIR}/${2}.crt" &&
+    chmod go=r "${CERT_DIR}/${2}.crt" &&
+    chmod go-rwx "${CERT_DIR}/${2}.key"
+}
+
+do-cert "${SERVER_ADDR}" 'nginx' &&
+do-cert "${SERVER_ADDR} OpenVPN" 'openvpn' &&
+
+
+openssl dhparam -outform PEM -out "${CERT_DIR}/dh2048.pem" 2048 &&
+chmod u=r "${CERT_DIR}/dh2048.pem" &&
+chmod go=r "${CERT_DIR}/dh2048.pem" &&
+cp "${CA_DIR}/ca/ca.crt" "${CERT_DIR}" &&
+cp "${CA_DIR}/ca/crl" "${CERT_DIR}"
